language: csharp
solution: Synker.sln
mono:
  - latest
  - 4.4.0
install:
  - nuget restore Synker.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Synker.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe ./test/UnitTest/bin/Release/UnitTest.dll
