language: csharp
solution: Synker.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 2.10.8
install:
  - nuget restore Synker.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Synker.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./test/UnitTest/bin/Release/UnitTest.dll
